### PR TITLE
1.0.1 release

### PR DESCRIPTION
**Pull request by somexpert**
Just added a change log so this is ready to be tagged as 1.0.1 release.

### CODE REVIEW

**Comment by somexpert** [comment]
@ldko, @damonkelley, this is ready for review, tiny though it may be.

**Comment by ldko** [comment]
We could link to the related issues from the change log.

**Comment by somexpert** [comment]
ooooh, that'd look nice. yep, I'll do that.

**Comment by ldko** [comment]
Also, would you add in about fixing typos in about.html to the log. Thank you!

**Pull request closed without merging**
