### PR TITLE
structure

### PR DESCRIPTION
**Pull request by somexpert**
This branch is for setting up the general structure of the app.

TO-DO:

- [x] Fill in setup.py
- [x] Fill in .travis.yml
- [x] Fill in MANIFEST.in
- [x] Create requirements file
- [x] Fill in tox.ini
- [x] Move tests to tests dir
- [x] Create django project in tests dir
- [x] Move manage.py to root of whole project

### CODE REVIEW

**Comment by somexpert** [comment]
@ldko, @damonkelley, this is ready for review. Just note that I haven't really begun working on making the code functional at all, this is strictly for structure. Functionality will be the next branch.

**Comment by ldko** [comment]
I will defer to @damonkelley on this one.

**Comment by damonkelley** [comment]
Looks like we don't have a version of Django that we are developing against. That should be in `requirements-dev.txt`.

**Comment by damonkelley** [comment]
Closing and reopening to force a Travis build.

**Comment by damonkelley** [comment]
Cool. looks good. 

One last thing.

What do you think about renaming `requirements-dev.txt` to `requirements.txt`?

**Comment by somexpert** [comment]
Works for me. And I won't skip the CI on this commit.

**Comment by damonkelley** [comment]
:+1:

**Pull request merged**
