### PR TITLE
Remove definition from PROPERTY_NAME_CHOICES.

### LINKED ISSUE #27: Remove "Definition" option
We have a choice option in `PROPERTY_NAME_CHOICES` of `definition` that we should remove. It has been replaced with `description` which is the preferred term. 

https://github.com/unt-libraries/django-controlled-vocabularies/blob/master/controlled_vocabularies/models.py#L12

There might be some references to this choice in the templates or other parts of the app that will need to be replaced with `description`. 

**Note:** there is a field named `definition` in the `Vocabulary` model.  This doesn't get changed and it shouldn't be confused in the templates when we are taking care of the choice `definition` mentioned above.

### PR DESCRIPTION
**Pull request by madhulika95b**
@somexpert @ldko 

This closes #27

### CODE REVIEW

**Review by somexpert — CHANGES_REQUESTED** [review]
I think I'd prefer to see the changes to the migrations removed, and instead a new migration created. We don't expect old migrations to stay current with the models, which is why they exist in the first place. We just need a new migration to reflect that this tiny change has been made.

FYI: This is an extra tidbit, but there's actually no real _need_ for even a new migration, as whatever shows up in the choices actually has no effect whatsoever. The choices are not in any way enforced in the database (last time I checked), it's purely done from within Django, which doesn't care about the migrations anyways. I think they just include that info in the migrations for any developers which might be looking through them manually so they can see when those choices changed. Or maybe those choices will at some point be enforced in the database? I don't know, I just know that last time I checked they weren't actually _doing_ anything in the migrations :smile:

**Review by ldko — COMMENTED** [review]
We may need to change our production and dev database data to change properties with the "definition" value to "description".

My review (that I started before Gio submitted) is basically redundant based on his, as I didn't really notice anything else!

**Review by ldko — APPROVED** [review]
Thanks for updating the changelog. This looks good to me!

**Review by somexpert — APPROVED** [review]
Looks good to me! :thumbsup:

**Pull request merged**
